### ISSUE TITLE
Update Reduceron to build and follow best practices for GHC/Cabal/Stack

### ISSUE THREAD

**Issue by tommythorn** [tommythorn/Reduceron#40]
As touched upon in #36, Reduceron doesn't build anymore due to changes to the GHC/Cabal/Stack.  Part of the problem is that Flite is effectively a separate project, but a mandatory requirement for Reduceron.

I don't have the expertise to resolve this, but it seems worthwhile to get it back to building, so as an experiment, I'm trying to provide an Algora bounty for this.  To make the requirement as clear as possible:
* Restore the ability to build everything and run all the regressions with a toplevel `make`
* Apply the current best practices for Haskell/GHC projects (sounds like using "stack" is a popular approach).

The workaround applied for #36 does not work for me.

/bounty $150

EDIT: typos

**Comment by tommythorn** [comment]
I'm new to Algora bounties, but it seems I should cancel @rishi-raj-jain 's attempt?  It doesn't look like he made any progress in over there months.

**Comment by ashish111333** [comment]
is this still open ? @tommythorn

**Comment by tommythorn** [comment]
yesTommyOn Dec 4, 2024, at 01:38, ashish ***@***.***> wrote:﻿
is this still open ? @tommythorn

**Comment by tommythorn** [comment]
Let's raise the stakes
/bounty $200

**Comment by tommythorn** [comment]
After years of nothing, I can have two fixes for this within 24 hours.  I'm not sure how to resolve this, but technically @Neptune650 was earlier.

**Comment by Neptune650** [comment]
> After years of nothing, I now have two fixes for this within 24 hours.  I'm not sure how to resolve this, but technically @Neptune650 was earlier.

@tommythorn I'd appreciate if you merge mine, as the other pull request was created after mine, does roughly the same changes and the commits were only created after mine.

**Comment by Neptune650** [comment]
> Thanks for your change. You also used the `/claim #40` so I think there's not much debate. I'm still evaluating this and hope to accept your change shortly.

@tommythorn Much appreciated! Let me know if you find any issues.

**Comment by tommythorn** [comment]
I'm a bit confused about how this is supposed to be set up.  I installed Stack with `curl -sSL https://get.haskellstack.org/ | sh` and assumed the correctly to install ghc was `stack install ghc` but after than `make` still doesn't find `runhaskell`.   Having CI is great, but I think I might need a hint for setting this up for manual use on Ubuntu (and macOS would be nice too).

**Comment by Neptune650** [comment]
> I'm a bit confused about how this is supposed to be set up. I installed Stack with `curl -sSL https://get.haskellstack.org/ | sh` and assumed the correctly to install ghc was `stack install ghc` but after than `make` still doesn't find `runhaskell`. Having CI is great, but I think I might need a hint for setting this up for manual use on Ubuntu (and macOS would be nice too).

@tommythorn I believe you have to use `stack setup` instead.

**Comment by Neptune650** [comment]
@tommythorn Thanks for merging, could you award it?

**Comment by tommythorn** [comment]
Of course I'm just trying to figure out how (I'll have to ran the door so it will be later today)

**Comment by Neptune650** [comment]
> Of course I'm just trying to figure out how (I'll have to ran the door so it will be later today) 

@tommythorn No worries!! You can send it from the Algora bounty panel.
