### ISSUE TITLE
Replace dead link for old Reduceron project web page

### ISSUE THREAD

**Issue by mn416** [tommythorn/Reduceron#41]
Hi @tommythorn, York seem to have deleted the old Reduceron project webpage (and many of the links it pointed to). I managed to find a copy in my archives and have rehosted it here: https://mn416.github.io/reduceron-project/. I'd be very grateful if you could update your README with the new link.

**Comment by tommythorn** [comment]
Thanks.

I’m on my phone right now, but I already long ago captured all the relevant docs in this very repo.  Moving the link to you is just repeating the problem of external dependencies.  I should either delete the reference or point to archive.org’s immutable copy.

**Comment by CatsAreFluffy** [comment]
Any updates?
